In [2]:
import numpy as np

$$\newcommand{mmx}[2]{\left[\begin{matrix}#1 \\ #2\end{matrix}\right]}$$ 
$$\newcommand{mmxx}[4]{\left[\begin{matrix}#1 & #3 \\ #2 & #4\end{matrix}\right]}$$ 
$$\newcommand{mmmx}[3]{\left[\begin{matrix} #1 \\ #2 \\ #3\end{matrix}\right]}$$ 

$$\newcommand{\u}{\mathbf{u}}$$ 
$$\newcommand{\v}{\mathbf{v}}$$ 
$$\newcommand{\w}{\mathbf{w}}$$ 
$$\newcommand{\R}{\mathbb{R}}$$

1) What combination $c\mmx{1}{2}+d\mmx{3}{1}$ produces $\mmx{14}{8}$? Express this question as two equations for the coefficients $c$ and $d$ in the linear combination.

c + 3d = 14  
2c + d = 8  
so c = 2, d = 4


2) Write the solution as a sum using `numpy`.

In [3]:
c = 2
d = 4
res = c * np.array([1,2]) + d * np.array([3,1])
print res

[14  8]


3) Can three vectors in the $xy$ plane (i.e. $\R^2$) have $\u\cdot\v < 0$, $\v\cdot\w < 0$, and $\u\cdot\w < 0$? I don't know how many vectors in $xyz$ (i.e. $\R^3$) space can have all negative dot products. (Four of those vectors in the plane would certainly be impossible ...).

No. it should not be possible. Two of them should be greater than zero

4) Find four perpendicular unit vectors with all components equal to $\frac{1}{2}$ or $-\frac{1}{2}$.

[1/2, -1/2, -1/2, 1/2]   
[1/2, 1/2, -1/2, -1/2]  
[-1/2, 1/2, 1/2, -1/2]  
[-1/2, -1/2, 1/2, 1/2]  

5) Use `numpy` to show that these vectors are unit vectors. 

In [4]:
from numpy import linalg as LA
r1 = [1.0/2, -1.0/2, -1.0/2, 1.0/2]
print "r1 lenght {}".format( LA.norm(r1, ord=2))

r1 lenght 1.0


6) Find a combination $\alpha\u+\beta\v+\gamma\w$ that gives the zero vector. 

\begin{align*}
\mathbf{u}&=\mmmx{1}{2}{3} & 
\mathbf{v}&=\mmmx{4}{5}{6} & 
\mathbf{w}&=\mmmx{7}{8}{9}
\end{align*}

Are $\u$, $\v$, $\w$ independent or dependent? Why? 

No, they are not. w = -1*u +  2*v

If the three vectors form a matrix $A$ with those columns, is it invertible?

No, it's not invertible


7) Write $A$ as a matrix in `numpy`. Display the matrix. 

**NOTE:** Conversation about row order vs. column order. 


In [5]:
u = np.array([1,2,3]).reshape((3,1))
v = np.array([4,5,6]).reshape((3,1))
w = np.array([7,8,9]).reshape((3,1))
res = np.concatenate((u,v,w), axis = 1)
print "column order {}".format(res) 
        
res = np.concatenate((u.transpose(),v.transpose(),w.transpose()), axis = 0)
print "row order {}".format(res)     

column order [[1 4 7]
 [2 5 8]
 [3 6 9]]
row order [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Markov Matrices

8) You should do this with `numpy`. Start with the vector $\u_0 = (1,0)$. Multiply again and again by the same "Markov matrix" 
$A =\mmxx{.8}{.2}{.3}{.7}$. Find $\u_i = A\u_{i-1}$ for $i\in[1,3]$

9) Write a `for` loop to do this through $\u_7$. What do you notice about $\u_7$?

u7 starts to stabilize in the sense u8, u9, ... are more or less the same.

10) There is a steady-state $\u_s$ where $A\u_s=\u_s$. Find it.  
u= [0,0]

In [7]:
#codes for question 9
print "############Question 9###########"
u0 = np.matrix([1,0]).transpose()
A = np.matrix([[0.8, 0.3], [0.2, 0.7]])
res = [u0]
for i in np.arange(1,10,1):
    temp = A * res[i-1]
    res.append(temp)
    print "u{} {}".format(i, temp)
    
# codes for question 10
#identtity_matrix = np.matrix([[1.0, 0.0], [0.0, 1.0]])
#A = np.matrix([[0.8, 0.3], [0.2, 0.7]])
#A = A - identtity_matrix
#b = np.matrix([0.0, 0.0]).transpose()
#u = LA.solve(A, b)
# since we have to start with u0=(1,0), above codes for quesion 10 should be incorrect
# We already observed that Au tends to stabilize, we could just repeat Au for sufficient number of times and get an appromiate steady state
print "############Question 10###########"
u0 = np.matrix([1,0]).transpose()
A = np.matrix([[0.8, 0.3], [0.2, 0.7]])
res = [u0]
for i in np.arange(1,101,1):
    temp = A * res[i-1]
    res.append(temp)
    print "u{} {}".format(i, temp)
print "steady state u {}".format(temp)

############Question 9###########
u1 [[ 0.8]
 [ 0.2]]
u2 [[ 0.7]
 [ 0.3]]
u3 [[ 0.65]
 [ 0.35]]
u4 [[ 0.625]
 [ 0.375]]
u5 [[ 0.6125]
 [ 0.3875]]
u6 [[ 0.60625]
 [ 0.39375]]
u7 [[ 0.603125]
 [ 0.396875]]
u8 [[ 0.6015625]
 [ 0.3984375]]
u9 [[ 0.60078125]
 [ 0.39921875]]
############Question 10###########
u1 [[ 0.8]
 [ 0.2]]
u2 [[ 0.7]
 [ 0.3]]
u3 [[ 0.65]
 [ 0.35]]
u4 [[ 0.625]
 [ 0.375]]
u5 [[ 0.6125]
 [ 0.3875]]
u6 [[ 0.60625]
 [ 0.39375]]
u7 [[ 0.603125]
 [ 0.396875]]
u8 [[ 0.6015625]
 [ 0.3984375]]
u9 [[ 0.60078125]
 [ 0.39921875]]
u10 [[ 0.60039063]
 [ 0.39960938]]
u11 [[ 0.60019531]
 [ 0.39980469]]
u12 [[ 0.60009766]
 [ 0.39990234]]
u13 [[ 0.60004883]
 [ 0.39995117]]
u14 [[ 0.60002441]
 [ 0.39997559]]
u15 [[ 0.60001221]
 [ 0.39998779]]
u16 [[ 0.6000061]
 [ 0.3999939]]
u17 [[ 0.60000305]
 [ 0.39999695]]
u18 [[ 0.60000153]
 [ 0.39999847]]
u19 [[ 0.60000076]
 [ 0.39999924]]
u20 [[ 0.60000038]
 [ 0.39999962]]
u21 [[ 0.60000019]
 [ 0.39999981]]
u22 [[ 0.6000001]
 [ 0.3999999]]
u23 [[ 0