# Homework #1

In [2]:
import numpy as np

1) What combination $c\begin{bmatrix}1 \\ 2\end{bmatrix}+d\begin{bmatrix}3\\1\end{bmatrix}$ produces $\begin{bmatrix}14 \\ 8\end{bmatrix}$? Express this question as two equations for the coefficients $c$ and $d$ in the linear combination.


$c+3d=14$ *(1)*

$2c+d=8$  *(2)*

$\implies d = 8-2c$ *(3)*

(3) inside (1) $\implies c + 24 - 6c = 14$

$\implies c = 10/5 = 2$ *(4)*

(4) inside (3) $\implies d = 8 - 4 = 4$

2) Write the solution as a sum using `numpy`.

In [ ]:
a = np.array([[1], [2]])
b = np.array([[3], [1]])
c = 2
d = 4
print(c*a+d*b)

3) Can three vectors in the $xy$ plane (i.e. $\mathbb R^2$) have $\mathbf u\cdot\mathbf v < 0$, $\mathbf v\cdot\mathbf w < 0$, and $\mathbf u\cdot\mathbf w < 0$? I don't know how many vectors in $xyz$ (i.e. $\mathbb R^3$) space can have all negative dot products. (Four of those vectors in the plane would certainly be impossible ...).

In [ ]:
a = np.array([0.620918, 0.641332])
b = np.array([-0.10042, -0.0587021])
c = np.array([2.5043, -2.58051])
print(np.dot(a,b))
print(np.dot(a,c))
print(np.dot(b,c))

In [ ]:
a = np.array([-0.0999437,-0.1, 0.741525])
b = np.array([0.221245, 0.420224, -0.1])
c = np.array([2.10005, -1.45848, -0.0999533])
d = np.array([-0.184675, -0.184683, -0.184667])
print(np.dot(a,b))
print(np.dot(a,c))
print(np.dot(a,d))
print(np.dot(b,c))
print(np.dot(b,d))
print(np.dot(c,d))

4) Find four perpendicular unit vectors with all components equal to $\frac{1}{2}$ or $-\frac{1}{2}$.

In [ ]:
a = np.array([-.5, .5, -.5, -.5])
b = np.array([-.5, -.5, -.5, .5])
c = np.array([-.5, -.5, .5, -.5])
d = np.array([.5, -.5, -.5, -.5])
print(np.dot(a,b))
print(np.dot(a,c))
print(np.dot(a,d))
print(np.dot(b,c))
print(np.dot(b,d))
print(np.dot(c,d))

5) Use `numpy` to show that these vectors are unit vectors. 

In [ ]:
print(np.dot(a,a))
print(np.dot(b,b))
print(np.dot(c,c))
print(np.dot(d,d))

6) Find a combination $\alpha\mathbf u+\beta\mathbf v+\gamma\mathbf w$ that gives the zero vector. 

\begin{align*}
\mathbf{u}&=\begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix} & 
\mathbf{v}&=\begin{bmatrix}4 \\ 5 \\ 6\end{bmatrix} & 
\mathbf{w}&=\begin{bmatrix}7 \\ 8 \\ 9\end{bmatrix}
\end{align*}

Are $\mathbf u$, $\mathbf v$, $\mathbf w$ independent or dependent? Why? 

If the three vectors form a matrix $A$ with those columns, is it invertible?


**Answer:**

Let's compute the determinant.
<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/caae8224e861040e4075b43438a5beee31b9f700">

In [ ]:
A = np.array([[1, 4, 7],[2, 5, 8],[3, 6, 9]])
print(A)
np.linalg.det(A)

Since the determinant is 0, the vectors are dependant. In addition, the matrix is not invertible. Source: http://www.math.harvard.edu/~elkies/M21b.08/det.html

7) Write $A$ as a matrix in `numpy`. Display the matrix. 

**NOTE:** Conversation about row order vs. column order. 

## Markov Matrices

8) You should do this with `numpy`. Start with the vector $\mathbf u_0 = (1,0)$. Multiply again and again by the same "Markov matrix" 
$A =\begin{bmatrix}.8 & .2 \\ .3 & .7\end{bmatrix}$. Find $\mathbf u_i = A\mathbf u_{i-1}$ for $i\in[1,3]$

In [3]:
A = np.array([[.8, .2],[.3, .7]])
u = np.array([[1],[0]])
for i in range(8):
    print("i = ", i, "u = ")
    print(u)
    print()
    u = np.dot(A,u)

i =  0 u = 
[[1]
 [0]]

i =  1 u = 
[[ 0.8]
 [ 0.3]]

i =  2 u = 
[[ 0.7 ]
 [ 0.45]]

i =  3 u = 
[[ 0.65 ]
 [ 0.525]]

i =  4 u = 
[[ 0.625 ]
 [ 0.5625]]

i =  5 u = 
[[ 0.6125 ]
 [ 0.58125]]

i =  6 u = 
[[ 0.60625 ]
 [ 0.590625]]

i =  7 u = 
[[ 0.603125 ]
 [ 0.5953125]]



9) Write a `for` loop to do this through $\mathbf u_7$. What do you notice about $\mathbf u_7$?

**Answer:**

$u_6$ and $u_7$ are close numerically. It seems like $u$ is converging to [.6, .6].

10) There is a steady-state $\mathbf u_s$ where $A\mathbf u_s=\mathbf u_s$. Find it.

In [8]:
A = np.array([[.8, .2],[.3, .7]])
u = np.array([[1],[0]])
print(u)
for i in range(999999):
    u = np.dot(A,u)
print(u)

[[1]
 [0]]
[[ 0.6]
 [ 0.6]]
