In [ ]:
import numpy as np

1) Perform one of the four types of matrix multiplication in `numpy`. Write your methods for $\mathbb R^2$.

**Answer:**  
use column based multiplication as below

In [7]:
import numpy as np
def question1_rsquare(R):
    column_num = R.shape[1]
    res = None
    for col in range(column_num):
        if res is None:
            res = R * R[:, col]
            continue
        res = np.concatenate((res, R* R[:, col]), axis = 1)
    return res
R = np.matrix([[1,2,3], [4,5,6] , [7,8,9]])
print "R*R = {}".format(R*R)
#column based calculation, the result is expected to be same as above
print "R*R = {}".format(question1_rsquare(R))

R*R = [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
R*R = [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


2) Write this system of linear equations as a matrix equation. Solve by careful inspection of the columns without doing any calculations.

\begin{align}
x+3y+2z&=-3\\
2x+2y+2z&=-2\\
2x+5y+6z&=-5
\end{align}

**Answer:**  
use column based multiplication, x = 0, y = -1, z=0

3) Find a point with $z=2$ on the intersection line of the planes $x+y+3z=6$ and $x-y+z=4$. Find the point with $z=0$. Find a third point halfway between.

**Answer:**  
z= 2, x= 1.0, y = -1.0  
z= 0, x= 5.0, y = 1.0  
z= 1, x= 3.0, y = -0.0


4) What is the 2 by 2 exchange matrix? 

$$P\begin{bmatrix}x\\ y\end{bmatrix}=\begin{bmatrix}y\\ x\end{bmatrix}$$

**Answer:**  
P = [[0 1]
 [1 0]]

5) What is the 2 by 2 matrix $R$ that rotates every vector by $90^{\circ}$? 

$$P\begin{bmatrix}x\\ y\end{bmatrix}=\begin{bmatrix}y\\ -x\end{bmatrix}$$

**Answer:**  

P = [[ 0  1]
 [-1  0]]


6) Use `numpy` to solve $A\mathbf{x}=\mathbf{b}$

$$A=\begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix} \ \ \ \ \mathbf{x}=\begin{bmatrix}5\\-2\end{bmatrix} \ \ \ \ \mathbf{b}=\begin{bmatrix}1\\7\end{bmatrix}$$

In [3]:
import numpy as np
from numpy import linalg as LA

A = np.matrix([[1, 2], [3, 4]])
b = np.matrix([1, 7]).transpose()
x = LA.solve(A, b)
print "x={}".format(x)

x=[[ 5.]
 [-2.]]


7) Solve this system by elimination and back substitution

\begin{align}
2x+3y&=1\\
10x+9y&=11
\end{align}

Use `numpy` to verify your answer.

**Answer:**
x = 2, y=-1

In [8]:
#verification codes
A = np.matrix([[2, 3], [10, 9]])
x = np.matrix([2, -1]).transpose()
b = A * x
#b is expected to be [1,11]
print "b: {}".format(b)

b: [[ 1]
 [11]]


8) Choose a right side which gives no solution. Choose another right side that gives infinitely many solutions.

\begin{align}
3x+2y&=10\\
6x+4y&=
\end{align}

How does `numpy` tell you there is no answer?

**Answer:**  
set anotehr right side as 20, numpy tells us there is no answer by throwing exception "numpy.linalg.linalg.LinAlgError: Singular matrix"

In [9]:
#An exception is expected to throw while executing below codes
A = np.matrix([[3, 2], [6, 4]])
b = np.matrix([10, 10]).transpose()
x = LA.solve(A, b)
print "x={}".format(x)

LinAlgError: Singular matrix

9) Which number $d$ forces a row exchange, and what is the triangular system (not singular) for that $d$? Which $d$ makes this system singular (no third pivot)?

\begin{matrix}
2x+5y+z&=0\\
4x+dy+z&=2\\
y-z&=3
\end{matrix}

**Answer:**  

d = 0 will force a row change  
d !=11 will make the matrix non singular  
d = 11 will make the system singular

10) For which three values of $a$ is $A$ singular?

$$A=\begin{bmatrix}a & 2 & 3\\ a & a & 4 \\ a & a & a\end{bmatrix}$$

**Answer:**  

a = 0,2,4 will make matrix A sigular

11) Write down the 3 by  3 matrices that produce these elimination steps:

- $E_{21}$ subtracts 5 times row 1 from row 2
- $E_{32}$ subtracts -7 times row 2 from row 3.
- $P$ exchanges rows 1 and 2, then rows 2 and 3.

**Answer:**  
E21 = np.matrix([[1,0,0], [-5,1,0] , [0,0,1]])  
E32 = np.matrix([[1,0,0], [0,1,0] , [0, 7, 1]])  
P = np.matrix([[0,1,0], [0,0,1] , [1,0,0]])

12) Multiply this matrix

$$
\begin{bmatrix}
0 & 0 & 1 \\ 
0 & 1 & 0 \\ 
1 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0 
\end{bmatrix}
=
$$

and this matrix

$$
\begin{bmatrix}
 1 & 0 & 0 \\
-1 & 1 & 0 \\
-1 & 0 & 1 
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
1 & 3 & 1 \\
1 & 4 & 0 
\end{bmatrix}
=
$$

**Answer:**  
1)  [[9 8 7]
 [6 5 4]
 [3 2 1]]  
 
2) [[ 1  2  3]
 [ 0  1 -2]
 [ 0  2 -3]]
 


13) Write this problem in matrix form, $A\mathbf{x}=b$, and solve it

$(x,y)=(2,5)$ and $(3,7)$ lie on the line $y=mx+c$. Find $m$ and $c$.

**Answer:**  
m=2.0, c=1.0

14) Find the triangular matrix $E$ that reduces "Pascal's matrix" to a smaller Pascal:

$$E
\begin{bmatrix}
 1 & 0 & 0 & 0 \\
 1 & 1 & 0 & 0 \\
 1 & 2 & 1 & 0 \\
 1 & 3 & 3 & 1 \\  
\end{bmatrix}
=
\begin{bmatrix}
 1 & 0 & 0 & 0 \\
 0 & 1 & 0 & 0 \\
 0 & 1 & 1 & 0 \\
 0 & 1 & 2 & 1 \\  
\end{bmatrix}
$$

Which matrix $M$ (multiplying several $E$'s reduces Pascal all the way to $I$?

**Answer:**  
E = np.matrix([[1,0,0,0], [-1,1,0,0], [0,-1,1,0], [0,0,-1,1]])  
M = [[ 1.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 1. -2.  1. -0.]
 [-1.  3. -3.  1.]]

15) Write $M = \begin{bmatrix}3 & 4 \\ 5 & 7\end{bmatrix}$ as a product of many factors of $A$ and $B$. 

$$A=\begin{bmatrix}1 & 0 \\ 1 & 1\end{bmatrix} \ \ \ \ \ \ B=\begin{bmatrix}1 & 1 \\ 0 & 1\end{bmatrix}$$


**Answer:** 
Not sure how to proceed with question for now



16) Have a look at the following use of `scipy`'s `lu` solver.

In [6]:
import scipy.linalg as sla
import numpy.random as rand

def random_3_by_3():
    return np.reshape(rand.rand(9),(3,3))

A = random_3_by_3()

P, L, U = sla.lu(A)
print(P),
print(L),
print(U)

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] [[ 1.          0.          0.        ]
 [ 0.13806458  1.          0.        ]
 [ 0.97743663 -0.38193743  1.        ]] [[ 0.6626936   0.88743582  0.13744239]
 [ 0.          0.72610561  0.80593419]
 [ 0.          0.          0.51321928]]


Find experimentally the first, second, and third pivots (i.e. for a new $A$ on each pass. What do you notice about $U_{11}$, $U_{22}$, and $U_{33}$? 

**NOTE**: *What we are looking for here is the general trend of the three pivots over possibly hundreds of iterations.*

**Answer:** 
Not sure how to proceed with question for now